ALTER TABLE shop_connections
  ADD COLUMN IF NOT EXISTS shop_name TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS shop_region TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS seller_type TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS shop_code TEXT NOT NULL DEFAULT '';
