import { useEffect, useState } from 'react'
import dayjs from 'dayjs'
import { AlertTriangle, CheckCircle2, ChevronRight, Download, RefreshCw, Send, Settings2, WalletCards } from 'lucide-react'
import { toast } from 'sonner'
import client from '@/api/client'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Card, CardContent } from '@/components/ui/card'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Switch } from '@/components/ui/switch'
import { PageHeader } from '@/components/common/PageHeader'
import { ConfirmDialog } from '@/components/common/ConfirmDialog'
import { useAuthStore } from '@/store/auth'

type Shop = { shop_id: string; shop_name: string; shop_code?: string; disabled?: boolean }
type Item = { id: string; order_id: string; sml_invoice_doc_no?: string; customer_code?: string; invoice_amount: number; settlement_amount: number; fee_amount: number; shipping_amount: number; adjustment_amount: number; refund_amount: number; currency: string; status: string; block_reason?: string; receipt_doc_no?: string }
type Run = { id: string; shop_id: string; shop_label: string; statement_id: string; payment_id: string; payment_status: string; currency: string; payment_time?: string; total_settlement_amount: number; invoice_amount_total: number; fee_amount_total: number; status: string; config_version: number; item_count?: number; rc_doc_no?: string; error_msg?: string; anomaly_reason?: string; items?: Item[] }
type Counts = { processing?: number; ready?: number; needs_review?: number; sent?: number; failed?: number; total: number }
type RouteSummary = { configured: boolean; doc_format_code?: string; passbook_code?: string; passbook_name?: string; bank_code?: string; bank_branch?: string; expense_code?: string; expense_name?: string }

const money = (v?: number, currency = 'THB') => new Intl.NumberFormat('th-TH', { style: 'currency', currency: /^[A-Z]{3}$/.test(currency) ? currency : 'THB' }).format(Number(v ?? 0))
const statusMeta: Record<string, { text: string; className: string }> = {
  importing: { text: 'กำลังดึงข้อมูล', className: 'bg-muted text-muted-foreground' }, reconciling: { text: 'กำลังตรวจยอด', className: 'bg-info/15 text-info' }, ready: { text: 'พร้อมส่ง', className: 'bg-success/15 text-success' }, needs_review: { text: 'ต้องตรวจ', className: 'bg-warning/15 text-warning' }, sending: { text: 'กำลังส่ง SML', className: 'bg-info/15 text-info' }, sent: { text: 'ส่งแล้ว', className: 'bg-success/15 text-success' }, failed: { text: 'ผิดพลาด', className: 'bg-destructive/15 text-destructive' }, unknown_result: { text: 'ต้องตรวจผล SML', className: 'bg-warning/15 text-warning' }, superseded: { text: 'ข้อมูลใหม่กว่า', className: 'bg-muted text-muted-foreground' },
}

export default function TikTokSettlement() {
  const isAdmin = useAuthStore((state) => state.user?.role === 'admin')
  const [shops, setShops] = useState<Shop[]>([]); const [shopID, setShopID] = useState(''); const [runs, setRuns] = useState<Run[]>([]); const [counts, setCounts] = useState<Counts>({ total: 0 }); const [loading, setLoading] = useState(true); const [selected, setSelected] = useState<Run | null>(null); const [route, setRoute] = useState<RouteSummary | null>(null); const [sendConfirmOpen, setSendConfirmOpen] = useState(false); const [sending, setSending] = useState(false); const [settingsOpen, setSettingsOpen] = useState(false); const [settingsConfirmOpen, setSettingsConfirmOpen] = useState(false); const [readEnabled, setReadEnabled] = useState(false); const [smlEnabled, setSmlEnabled] = useState(false); const [settingsVersion, setSettingsVersion] = useState(0)
  const [from, setFrom] = useState(dayjs().subtract(14, 'day').format('YYYY-MM-DD')); const [to, setTo] = useState(dayjs().format('YYYY-MM-DD')); const [runStatus, setRunStatus] = useState('all'); const [paymentStatus, setPaymentStatus] = useState('all')
  const load = async () => { setLoading(true); try { const params = { ...(shopID ? { shop_id: shopID } : {}), date_from: from, date_to: to, ...(runStatus !== 'all' ? { status: runStatus } : {}), ...(paymentStatus !== 'all' ? { payment_status: paymentStatus } : {}) }; const [connections, list, summary] = await Promise.all([client.get<{ data: Shop[] }>('/api/tiktok-shop-api/local-connections'), client.get<{ data: Run[] }>('/api/tiktok-settlements', { params }), client.get<Counts>('/api/tiktok-settlements/counts')]); const active = (connections.data.data ?? []).filter(s => !s.disabled); setShops(active); if (!shopID && active.length === 1) setShopID(active[0].shop_id); setRuns(list.data.data ?? []); setCounts(summary.data) } catch (e: any) { toast.error(e?.response?.data?.error?.message ?? 'โหลดรายการรับชำระ TikTok Shop ไม่สำเร็จ') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [shopID, from, to, runStatus, paymentStatus])
  const preflight = async () => { if (!shopID) return toast.error('กรุณาเลือกร้านก่อนตรวจระบบ'); try { const r = await client.post<{ data: { message: string } }>('/api/tiktok-settlements/preflight', null, { params: { shop_id: shopID } }); toast.success(r.data.data.message) } catch (e: any) { toast.error(e?.response?.data?.error?.message ?? 'ตรวจระบบไม่สำเร็จ') } }
  const importStatements = async () => { if (!shopID) return toast.error('กรุณาเลือกร้านก่อนดึง Statement'); try { const r = await client.post('/api/tiktok-settlements/import', { shop_id: shopID, date_from: from, date_to: to }); toast.success(r.data.message ?? 'เริ่มดึง Statement แล้ว'); await load() } catch (e: any) { toast.error(e?.response?.data?.error?.message ?? 'ดึง Statement ไม่สำเร็จ') } }
  const openSettings = async () => { if (!shopID) return toast.error('กรุณาเลือกร้านก่อนตั้งค่า'); try { const r = await client.get<{ data: { read_enabled: boolean; sml_send_enabled: boolean; config_version: number } }>('/api/tiktok-settlements/settings', { params: { shop_id: shopID } }); setReadEnabled(r.data.data.read_enabled); setSmlEnabled(r.data.data.sml_send_enabled); setSettingsVersion(r.data.data.config_version); setSettingsOpen(true) } catch { toast.error('โหลดการตั้งค่าร้านไม่สำเร็จ') } }
  const saveSettings = () => setSettingsConfirmOpen(true)
  const confirmSaveSettings = async () => { try { await client.put(`/api/tiktok-settlements/settings/${shopID}`, { read_enabled: readEnabled, sml_send_enabled: smlEnabled, expected_config_version: settingsVersion }); toast.success('บันทึกการตั้งค่าแล้ว'); setSettingsOpen(false) } catch (e: any) { toast.error(e?.response?.data?.error?.message ?? 'บันทึกการตั้งค่าไม่สำเร็จ') } }
  const open = async (run: Run) => { try { const [detail, routeResult] = await Promise.all([client.get<{ data: Run }>(`/api/tiktok-settlements/${run.id}`), client.get<{ data: RouteSummary }>('/api/tiktok-settlements/route')]); setSelected(detail.data.data); setRoute(routeResult.data.data) } catch { toast.error('โหลดรายละเอียด Statement ไม่สำเร็จ') } }
  const reconcile = async () => { if (!selected) return; try { const r = await client.post<{ data: Run }>(`/api/tiktok-settlements/${selected.id}/reconcile`); setSelected(r.data.data); await load(); toast.success('ตรวจเทียบ Statement ล่าสุดแล้ว') } catch (e: any) { toast.error(e?.response?.data?.error?.message ?? 'ตรวจเทียบไม่สำเร็จ') } }
  const send = () => setSendConfirmOpen(true)
  const confirmSend = async () => { if (!selected) return; setSending(true); try { await client.post(`/api/tiktok-settlements/${selected.id}/send`, { confirm: 'CONFIRM_TIKTOK_RC', expected_config_version: String(selected.config_version) }); toast.success('เริ่มส่ง RC เข้า SML แล้ว'); setSelected(null); await load() } catch (e: any) { toast.error(e?.response?.data?.error?.message ?? 'ส่ง RC ไม่สำเร็จ') } finally { setSending(false) } }
  return <div className="space-y-4 p-0 sm:p-0">
    <PageHeader title="รับชำระ TikTok Shop" description="TikTok แจ้งว่าโอนแล้ว → ตรวจยอดทั้ง Statement → ยืนยันส่งรับชำระหนี้ (RC) เข้า SML" />
    <Card className="border-border/70 shadow-none"><CardContent className="flex flex-wrap items-end gap-3 p-4"><div className="min-w-[220px] flex-1 space-y-1"><Label>ร้าน TikTok Shop</Label><Select value={shopID} onValueChange={setShopID}><SelectTrigger><SelectValue placeholder="เลือกร้าน" /></SelectTrigger><SelectContent>{shops.map(s => <SelectItem key={s.shop_id} value={s.shop_id}>{s.shop_name || s.shop_id}</SelectItem>)}</SelectContent></Select></div><div className="space-y-1"><Label>ตั้งแต่</Label><Input type="date" value={from} onChange={e => setFrom(e.target.value)} /></div><div className="space-y-1"><Label>ถึง</Label><Input type="date" value={to} onChange={e => setTo(e.target.value)} /></div><div className="min-w-[145px] space-y-1"><Label>สถานะ Statement</Label><Select value={paymentStatus} onValueChange={setPaymentStatus}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">ทุกสถานะ</SelectItem><SelectItem value="PAID">TikTok โอนแล้ว</SelectItem><SelectItem value="PROCESSING">รอ TikTok โอน</SelectItem><SelectItem value="FAILED">TikTok โอนไม่สำเร็จ</SelectItem></SelectContent></Select></div><div className="min-w-[135px] space-y-1"><Label>สถานะงาน</Label><Select value={runStatus} onValueChange={setRunStatus}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">ทุกสถานะ</SelectItem><SelectItem value="ready">พร้อมส่ง</SelectItem><SelectItem value="needs_review">ต้องตรวจ</SelectItem><SelectItem value="sent">ส่งแล้ว</SelectItem><SelectItem value="failed">ผิดพลาด</SelectItem></SelectContent></Select></div><Button variant="outline" onClick={preflight}><CheckCircle2 className="mr-2 h-4 w-4" />ตรวจระบบ</Button><Button onClick={importStatements}><Download className="mr-2 h-4 w-4" />ดึง Statement</Button>{isAdmin && <Button variant="outline" onClick={openSettings}><Settings2 className="mr-2 h-4 w-4" />ตั้งค่าร้าน</Button>}<Button variant="outline" size="icon" onClick={() => void load()} aria-label="รีเฟรช"><RefreshCw className="h-4 w-4" /></Button></CardContent></Card>
    <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-5">{[['รอ TikTok โอน', counts.processing], ['พร้อมส่ง', counts.ready], ['ต้องตรวจ', counts.needs_review], ['ส่งแล้ว', counts.sent], ['ผิดพลาด', counts.failed]].map(([label, value]) => <Card key={String(label)} className="shadow-none"><CardContent className="p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-semibold">{Number(value ?? 0)}</p></CardContent></Card>)}</div>
    <Card className="shadow-none"><CardContent className="p-0">{loading && <div className="p-6 text-sm text-muted-foreground">กำลังโหลด Statement…</div>}<div className="hidden overflow-x-auto md:block"><table className="w-full text-sm"><thead className="border-b bg-muted/30 text-left text-muted-foreground"><tr><th className="p-3">Statement / วันที่</th><th className="p-3">ร้าน</th><th className="p-3 text-right">ยอด TikTok / Order</th><th className="p-3">สถานะ</th><th className="p-3">RC</th><th className="p-3" /></tr></thead><tbody>{runs.map(run => <tr key={run.id} className="border-b last:border-0"><td className="p-3"><p className="font-medium">{run.statement_id}</p><p className="text-xs text-muted-foreground">{run.payment_time ? dayjs(run.payment_time).format('DD/MM/YY HH:mm') : '-'}</p></td><td className="p-3"><Badge className="border-[#111817] bg-[#111817] text-white hover:bg-[#111817]">TikTok</Badge><p className="mt-1 text-xs text-muted-foreground">{run.shop_label}</p></td><td className="p-3 text-right"><p className="font-medium">{money(run.total_settlement_amount, run.currency)}</p><p className="text-xs text-muted-foreground">{run.item_count ?? '-'} order</p></td><td className="p-3"><Badge variant="secondary" className={statusMeta[run.status]?.className}>{statusMeta[run.status]?.text ?? run.status}</Badge><p className="mt-1 max-w-[200px] truncate text-xs text-muted-foreground">{run.anomaly_reason || run.error_msg}</p></td><td className="p-3 text-xs">{run.rc_doc_no || '-'}</td><td className="p-3 text-right"><Button size="sm" variant="outline" onClick={() => void open(run)}>รายละเอียด<ChevronRight className="ml-1 h-4 w-4" /></Button></td></tr>)}</tbody></table></div><div className="divide-y md:hidden">{runs.map(run => <button key={run.id} onClick={() => void open(run)} className="w-full p-4 text-left"><div className="flex items-start justify-between gap-3"><div><p className="font-medium">{run.statement_id}</p><p className="mt-1 text-xs text-muted-foreground">{run.shop_label} · {money(run.total_settlement_amount, run.currency)}</p></div><Badge variant="secondary" className={statusMeta[run.status]?.className}>{statusMeta[run.status]?.text ?? run.status}</Badge></div></button>)}</div>{!loading && runs.length === 0 && <div className="p-10 text-center text-sm text-muted-foreground">ยังไม่มี Statement ในช่วงนี้ — การเปิดหน้านี้จะไม่เรียก TikTok Finance อัตโนมัติ</div>}</CardContent></Card>
    <Dialog open={!!selected} onOpenChange={v => !v && setSelected(null)}><DialogContent className="max-h-[90vh] max-w-3xl overflow-y-auto"><DialogHeader><DialogTitle className="flex items-center gap-2"><WalletCards className="h-5 w-5" />Statement {selected?.statement_id}</DialogTitle><DialogDescription>TikTok แจ้งว่าโอนแล้ว เป็นหลักฐานจากแพลตฟอร์ม ไม่ใช่การยืนยันจาก statement ธนาคาร</DialogDescription></DialogHeader>{selected && <div className="space-y-4"><div className="grid grid-cols-2 gap-3 text-sm sm:grid-cols-4"><Metric label="ยอดใบขาย SML" value={money(selected.invoice_amount_total)} /><Metric label="TikTok โอน" value={money(selected.total_settlement_amount)} /><Metric label="Fee / commission" value={money(selected.fee_amount_total)} /><Metric label="Payment ID" value={selected.payment_id || '-'} /></div>{(selected.anomaly_reason || selected.error_msg) && <div className="flex gap-2 rounded-md border border-warning/30 bg-warning/5 p-3 text-sm text-warning"><AlertTriangle className="h-4 w-4 shrink-0" />{selected.anomaly_reason || selected.error_msg}</div>}<div className="rounded-md border"><div className="grid grid-cols-[1fr_auto_auto] gap-2 border-b p-2 text-xs text-muted-foreground"><span>คำสั่งซื้อ / ใบขาย SML</span><span>ยอด TikTok</span><span>ผลตรวจ</span></div>{(selected.items ?? []).map(i => <div key={i.id} className="grid grid-cols-[1fr_auto_auto] gap-2 border-b p-2 text-sm last:border-0"><div className="min-w-0"><p className="truncate">{i.order_id}</p><p className="truncate text-xs text-muted-foreground">{i.sml_invoice_doc_no || i.block_reason || 'รอตรวจ SML'}</p></div><span>{money(i.settlement_amount)}</span><Badge variant="secondary" className={i.status === 'ready' || i.status === 'sent' ? 'bg-success/15 text-success' : 'bg-warning/15 text-warning'}>{i.status === 'ready' ? 'ผ่าน' : i.status === 'sent' ? 'ส่งแล้ว' : 'ต้องตรวจ'}</Badge></div>)}</div></div>}<DialogFooter className="gap-2"><Button variant="outline" onClick={() => void reconcile()} disabled={!selected || selected.status === 'sent'}>ตรวจเทียบใหม่</Button><Button onClick={() => void send()} disabled={sending || selected?.status !== 'ready' || !route?.configured}><Send className="mr-2 h-4 w-4" />ยืนยันส่ง RC เข้า SML</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={settingsOpen} onOpenChange={setSettingsOpen}><DialogContent><DialogHeader><DialogTitle>ตั้งค่ารับชำระ TikTok Shop</DialogTitle><DialogDescription>เปิดอ่านเพื่อดึง Statement ก่อน ส่วนส่ง SML ยังคงต้องให้พนักงานกดยืนยันทีละ Statement</DialogDescription></DialogHeader><div className="space-y-4 py-2"><div className="flex items-center justify-between gap-4"><div><p className="text-sm font-medium">อนุญาตอ่านข้อมูลการเงิน</p><p className="text-xs text-muted-foreground">ใช้กับตรวจระบบและดึง Statement ด้วยมือ</p></div><Switch checked={readEnabled} onCheckedChange={setReadEnabled} /></div><div className="flex items-center justify-between gap-4"><div><p className="text-sm font-medium">อนุญาตส่ง RC เข้า SML</p><p className="text-xs text-muted-foreground">ยังไม่มี Auto RC และต้องยืนยันก่อนส่งทุกครั้ง</p></div><Switch checked={smlEnabled} onCheckedChange={setSmlEnabled} disabled={!readEnabled} /></div></div><DialogFooter><Button variant="outline" onClick={() => setSettingsOpen(false)}>ยกเลิก</Button><Button onClick={saveSettings}>บันทึกการตั้งค่า</Button></DialogFooter></DialogContent></Dialog>
    <ConfirmDialog open={settingsConfirmOpen} onOpenChange={setSettingsConfirmOpen} title="ยืนยันเปลี่ยนการตั้งค่าร้าน" description={`ร้านนี้จะ${readEnabled ? '' : 'ไม่'}อนุญาตให้อ่าน Statement และ${smlEnabled ? '' : 'ไม่'}อนุญาตให้ส่ง RC เข้า SML\n\nการส่ง RC ยังต้องยืนยันทีละ Statement เสมอ และไม่มี Auto RC`} confirmLabel="ยืนยันบันทึก" onConfirm={confirmSaveSettings} />
    <ConfirmDialog open={sendConfirmOpen} onOpenChange={setSendConfirmOpen} title="ยืนยันสร้าง RC เข้า SML" description={selected ? `TikTok แจ้งว่าโอนแล้วสำหรับ Statement ${selected.statement_id}\nPayment ID: ${selected.payment_id || '-'}\n${selected.items?.length ?? selected.item_count ?? 0} คำสั่งซื้อ · ยอด TikTok ${money(selected.total_settlement_amount, selected.currency)}\nรูปแบบ RC: ${route?.doc_format_code || '-'} · บัญชีรับเงิน: ${route?.passbook_name || route?.passbook_code || '-'}\nค่าใช้จ่าย TikTok: ${route?.expense_name || route?.expense_code || '-'}\n\nการยืนยันนี้จะสร้างเอกสารรับชำระหนี้ใน SML และไม่มี Auto RC` : ''} confirmLabel="ยืนยันส่ง RC" onConfirm={confirmSend} />
  </div>
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-md bg-muted/40 p-2"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 truncate text-sm font-semibold">{value}</p></div> }
